cluster_config:
  name: argo-k8s

sysdig_endpoint:
  region: us4
  access_key_existing_secret: sysdig-credentials  # ← Secret 이름 참조

features:
  kubernetes_metadata:
    enabled: true
  posture:
    host_posture:
      enabled: true
    cluster_posture:
      enabled: true
  vulnerability_management:
    host_vulnerability_management:
      enabled: true
    container_vulnerability_management:
      enabled: true
    in_use:
      enabled: true
  detections:
    drift_control:
      enabled: true
    malware_control:
      enabled: true
    file_integrity_monitoring:
      enabled: true
    ml_policies:
      enabled: true
    kubernetes_audit:
      enabled: true
  investigations:
    activity_audit:
      enabled: true
    live_logs:
      enabled: true
    captures:
      enabled: true
  respond:
    response_actions:
      enabled: true

host:
  driver: legacy_ebpf